import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/pagesixteen">PageSixteen</Link>
        </li>
        <li>
          <Link to="/pageseven">PageSeven</Link>
        </li>
        <li>
          <Link to="/pagefifteen">PageFifteen</Link>
        </li>
        <li>
          <Link to="/pageeleven">PageEleven</Link>
        </li>
        <li>
          <Link to="/page">Page</Link>
        </li>
        <li>
          <Link to="/one">One</Link>
        </li>
        <li>
          <Link to="/posone">PosOne</Link>
        </li>
        <li>
          <Link to="/pos">Pos</Link>
        </li>
        <li>
          <Link to="/ecommerceappone">EcommerceappOne</Link>
        </li>
        <li>
          <Link to="/ecommerceapp">Ecommerceapp</Link>
        </li>
        <li>
          <Link to="/clinicsystem">Clinicsystem</Link>
        </li>
        <li>
          <Link to="/clinicsystemone">ClinicsystemOne</Link>
        </li>
        <li>
          <Link to="/one1">One1</Link>
        </li>
        <li>
          <Link to="/two">Two</Link>
        </li>
        <li>
          <Link to="/oneone">OneOne</Link>
        </li>
        <li>
          <Link to="/twoone">TwoOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
